"""Ajout du champ is_approved

Revision ID: 0922982c0931
Revises: 0bc1bcb58503
Create Date: 2025-05-09 15:08:40.380624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0922982c0931'
down_revision = '0bc1bcb58503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plat', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('plat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
